load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

platform(
    name = "android_arm64",
    constraint_values = [
        "@platforms//cpu:aarch64",
        "@platforms//os:android",
    ],
)

cc_library(
    name = "argparse",
    hdrs = glob(["include/argparse/**/*.hpp"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "boot",
    srcs = [
        "src/boot/prase.cc",
        "src/boot/unpack.cc",
        "src/boot/replace.cc",
        "src/boot/gzip.cc",
        "src/boot/bzip2.cc",
        "src/boot/lz4.cc",
        "src/boot/lzma.cc",
        "src/boot/lzop.cc",
    ],
    hdrs = [
        "include/boot/boot.hpp",
        "src/boot/boot_internal.hpp",
        "src/boot/bootimg.h",
    ],
    includes = ["include"],
    deps = [
    "//third_party:bzip2",
    "//third_party:lz4_file",
    "//third_party:lzo",
    "//third_party:xz",
    "//third_party:zlib",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "module",
    srcs = [
        "src/module/module.cc",
        "src/module/sepolicy.cc",
        "src/module/utils.cc",
        "src/module/zip.cc",
    ],
    hdrs = [
        "include/module/module.hpp",
        "src/module/module_internal.hpp",
        "src/module/zip.hpp",
    ],
    includes = ["include"],
    deps = [
        "//third_party:xz",
        "//third_party:zlib",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "cli",
    srcs = ["src/cli/cli.cc"],
    hdrs = ["include/cli.hpp"],
    includes = ["include"],
    deps = [
        ":argparse",
        ":boot",
        ":module",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "su",
    srcs = ["src/su/su.cc"],
    hdrs = ["include/su/su.hpp"],
    includes = ["include"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "ncore",
    srcs = ["src/main.cc"],
    deps = [
        ":cli",
        ":su",
    ],
    visibility = ["//visibility:public"],
)